version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - cd server
      - npm install
      - cd ..
      - cd client
      - npm install
      - npm run-script build